# Lesson 5 Practical Application
## C2C Jordan Armstrong
### Documentation: None.

In [12]:
from datascience import *
import numpy as np

Question 1: Create an array containing 4 string elements: your first name, your last name, your birth state and your favorite color.

    a) Use a numpy function to make all elements uppercase.
    
    b) Use a numpy function to count the number of times the letter "a" appears in each element of your array.
    
    c) Optional: Use a numpy function to find the length of each element in the array. You may need to Google this. 

In [13]:
Array=make_array('Jordan','Armstrong','Florida','Blue')
Array

array(['Jordan', 'Armstrong', 'Florida', 'Blue'], dtype='<U9')

Part a)

In [14]:
Upper=np.char.upper(Array)
Upper

array(['JORDAN', 'ARMSTRONG', 'FLORIDA', 'BLUE'], dtype='<U9')

In [18]:
Count_a=np.char.count(Array,'a')
Count_a

array([1, 0, 1, 0])

Optional.

Question 2: Create an array containing EVERY OTHER odd number starting with 1 and ending with (and including) 41.

    a) Use numpy to find the sum and the product of the elements of this array. NOTE: THis will require you to convert the elements of your array to floats using astype method.
    
    b) Use numpy to take the natural log of each element.
    
    c) Optional: The numpy function np.diff finds the difference between elements of an array. Find the SUM of adjacent elements of this array.

In [49]:
Odd_array=np.arange(1,42,4)
Odd_array

array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37, 41])

Part a)

In [53]:
Odd_array=Odd_array.astype(float)

In [54]:
Sum=numpy.sum(Odd_array)
Sum

231.0

In [55]:
Multiply=numpy.prod(Odd_array)
Multiply

7579867420125.0

Part b)

In [56]:
Nat_log=numpy.log(Odd_array)
Nat_log

array([0.        , 1.60943791, 2.19722458, 2.56494936, 2.83321334,
       3.04452244, 3.21887582, 3.36729583, 3.49650756, 3.61091791,
       3.71357207])

Part c)

Optional.